apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-o81i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-o81i
    app.kubernetes.io/part-of: ci1t-43256-0049-app
  name: devfile-sample-o81id5sp
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-o81i
    weight: null
status: {}
